apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    name: registry4
  name: registry4
spec:
  replicas: 1
  selector:
    name: registry4
  template:
    metadata:
      labels:
        name: registry4
    spec:
      containers:
      - env:
        - name: REGISTRY_HTTP_SECRET
          value: lhl4477
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: registry-zhongxin
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          value: AKIAOTLAH3GNC2A7AGVA
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          value: 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
        - name: REGISTRY_STORAGE_S3_REGION
          value: cn-north-1
        image: caicloud/harbor_registry:2.3.0
        imagePullPolicy: Always
        name: registry4
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/registry
          name: portus-config
      dnsPolicy: ClusterFirst
      nodeSelector:
        node: node-3.11
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: portus-config
        secret:
          secretName: portus-config4
status:
  replicas: 0
